spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

security:
  security:
    rate-limit:
      enabled: true
      login:
        capacity: 5
        refill-tokens: 5
        refill-minutes: 1
      register:
        capacity: 3
        refill-tokens: 3
        refill-minutes: 1
  jwt:
    secret: uEL6EtXq372fr5OhANdtLMJqnIcsUuaYYSVQLZOMWXdEQYyhs45WlC23vqkaov7xl+EiIgG1Y59RRvoKuNIwNA==
    expiration-ms: 86400000