CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(20) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       display_name VARCHAR(20) NOT NULL,
                       role VARCHAR(20) NOT NULL,
                       enabled BOOLEAN NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,

                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(30) NOT NULL,
                       description VARCHAR(2000),
                       status VARCHAR(255) NOT NULL,
                       priority VARCHAR(255) NOT NULL,
                       owner_id BIGINT NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                       CONSTRAINT pk_tasks PRIMARY KEY (id),

                       CONSTRAINT fk_tasks_owner
                           FOREIGN KEY (owner_id)
                               REFERENCES users (id)
                               ON DELETE CASCADE
);

CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          text VARCHAR(2000) NOT NULL,
                          task_id BIGINT NOT NULL,
                          author_id BIGINT NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL,

                          CONSTRAINT pk_comments PRIMARY KEY (id),

                          CONSTRAINT fk_comments_task
                              FOREIGN KEY (task_id)
                                  REFERENCES tasks (id)
                                  ON DELETE CASCADE,

                          CONSTRAINT fk_comments_author
                              FOREIGN KEY (author_id)
                                  REFERENCES users (id)
                                  ON DELETE CASCADE
);

CREATE INDEX idx_tasks_owner_id
    ON tasks (owner_id);

CREATE INDEX idx_comments_task_id
    ON comments (task_id);

CREATE INDEX idx_comments_author_id
    ON comments (author_id);